### ISSUE TITLE
Add pre-commit hook

### ISSUE THREAD

**Issue by rpdelaney** [lirantal/anti-trojan-source#2]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Provide a pre-commit hook. Would you accept a PR for this?

**Describe alternatives you've considered**
None.

**Comment by lirantal** [comment]
Hi @rpdelaney, can you explain what do you mean by adding a recommit to this project?
I know what precommit hooks are, and I'd imagine a JavaScript project would want to use something like `husky` to define them, and then run them.

**Comment by rpdelaney** [comment]
The (arguably) unfortunately named tool [pre-commit](https://pre-commit.com/) is a cli utility that allows a project to define git hooks using a yaml configuration file that can be added to source control. This helps a collaborative project ensure that everyone is using the same checks.

**Comment by lirantal** [comment]
@rpdelaney oh got it! Yes I'd definitely be happy to accept a PR to the project if you wanted to send it and create an integration with the `pre-commit` tool.
