### ISSUE TITLE
CLI help text does not match implementation

### ISSUE THREAD

**Issue by dannyvv** [lirantal/anti-trojan-source#3]
## Expected Behavior

Help text and examples should show `--files, -f` to match the code. 

## Current Behavior

1. npx anti-trojan-source  --help
    * Result:
    ![image](https://user-images.githubusercontent.com/11037542/142564672-548b1317-96ac-429c-abef-f280222609c8.png)
    * Note the text `Returns results as JSON`
    * Note the indentation in the examples section is slightly off
   
2. npx anti-trojan-source --filesPattern=**/*.js
    * Result: App hangs waiting for std-in, because it finds no files in the argument list, nor any known other arguments.
    
## Possible Solution

* Update the HelpText to display `--files, -f`.
* Fix the indentation in the examples section

## Steps to Reproduce (for bugs)

1. npx anti-trojan-source  --help
    Expected:
    *  Help to show `--files, -f` to reflect the code
    *  Help to show the proper description of the argument i.e. `File pattern of files to check.`

## Context

I ran into it the mismatch and wanted to fix it, so filing the issue to comply with pr steps.

## Your Environment

- Library Version used: `GH sources @ ce3d26a5abbe11661a8562d10dc2d7c4d003a8a0`
- Node.js version (e.g. Node.js 5.4): `v16.13.0`
- Operating System and version (desktop or mobile): `Windows 11 Desktop`

**Comment by lirantal** [comment]
Ahhhh yes! Good catch @dannyvv, thank you 🙏🏼
